package com.zzx.docrag.rag;

import com.zzx.docrag.config.LlmProperties;
import com.zzx.docrag.retrieve.Merged;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Builds the grounded prompt and parses citations back out of the answer.
 *
 * <p><b>Why excerpts are lettered [A], [B], [C] instead of numbered [1], [2], [3]</b> —
 * this design was driven by two measured failures, and the story is worth keeping:
 * <ol>
 *   <li>With numeric labels, the model cited the document's own section numbers: asked about
 *       a fact in section "三、制动盘检查标准", it answered with "[3]" although only one
 *       excerpt ([1]) existed. Citation accuracy collapsed to 0.</li>
 *   <li>Renaming labels to [S1], [S2] did not help: the model read "S" as "Section" and
 *       emitted "[S3]" for the same question. Any label containing a digit competes with
 *       the digits inside the document text.</li>
 * </ol>
 * Letters cannot collide with section numbers, clause numbers or page numbers, which removes
 * the ambiguity at the token level instead of arguing with the model through instructions.
 *
 * <p><b>Why citation attempts are counted broadly.</b> A strict parser that only recognizes
 * well-formed labels silently scores 100% when the model emits a malformed citation — the
 * metric goes blind exactly when the model misbehaves. So every short bracketed token counts
 * as a citation attempt, and an attempt that does not resolve to an excerpt label is recorded
 * as invalid. False positives (a legitimate bracketed aside of <= 6 characters) are accepted
 * as the price of an honest metric.
 *
 * <p>Other prompt decisions:
 * <ul>
 *   <li><b>Explicit refusal path.</b> Without an instruction to refuse, a model invents an
 *       answer rather than admitting a retrieval failure. Refusal accuracy is a metric.</li>
 *   <li><b>Context budget.</b> Chunks are added until {@code maxContextChars} is reached,
 *       which caps cost and keeps the prompt inside the model window even when top-K is large.</li>
 * </ul>
 */
@Component
public class PromptBuilder {

    /**
     * Any short bracketed token counts as a citation attempt: [A], [ A ], [3], [S3].
     * Broad on purpose - see the class javadoc on metric blindness.
     */
    private static final Pattern ATTEMPT = Pattern.compile("\\[[^\\[\\]]{1,6}]");

    /** A well-formed excerpt label: one or two letters, optional inner spaces. */
    private static final Pattern LABEL = Pattern.compile("[A-Za-z]{1,2}");

    private static final String REFUSAL_SENTINEL = "INSUFFICIENT_CONTEXT";

    /**
     * Bump this whenever the user-prompt TEMPLATE changes shape (not its dynamic content).
     * The answer cache fingerprints systemPrompt + this constant; without the constant, a
     * template-only change silently keeps serving answers generated by the old template.
     * That exact trap happened once during development - hence the pinned rule.
     */
    public static final String TEMPLATE_VERSION = "v2-letters-whitelist";

    private final LlmProperties llmProperties;

    public PromptBuilder(LlmProperties llmProperties) {
        this.llmProperties = llmProperties;
    }

    public String systemPrompt() {
        return """
                You are a technical documentation assistant.
                Answer strictly from the lettered excerpts provided by the user.

                Rules:
                1. Cite every factual claim with the label of the excerpt you used, for
                   example [A] or [B][C]. Valid labels are ONLY the letter markers at the
                   very start of each excerpt. Numbers in brackets are NOT valid labels;
                   section, clause and page numbers inside the excerpt text are NOT labels.
                2. Never state anything that is not supported by the excerpts. Do not use outside knowledge.
                3. If the excerpts do not contain the answer, reply with exactly %s and nothing else.
                4. Answer in the same language as the question.
                5. Be concise and concrete. Prefer steps, values and units over prose.
                """.formatted(REFUSAL_SENTINEL);
    }

    /**
     * @param question the user question
     * @param chunks   ranked chunks to ground the answer in
     * @return the user prompt, or a prompt that already declares insufficient context
     */
    public String userPrompt(String question, List<Merged> chunks) {
        StringBuilder context = new StringBuilder();
        List<String> labels = new ArrayList<>();
        int used = 0;
        for (int i = 0; i < chunks.size(); i++) {
            Merged chunk = chunks.get(i);
            // The header deliberately avoids the word "section": measured behaviour showed the
            // model mapping in-text section numbers ("三、...") onto citation labels.
            String block = "[%s] (document: %s, chunk: %s)%n%s%n%n"
                    .formatted(label(i), chunk.title(), chunk.chunkId(), chunk.content());
            if (used + block.length() > llmProperties.maxContextChars()) {
                break;
            }
            context.append(block);
            labels.add("[" + label(i) + "]");
            used += block.length();
        }

        if (context.isEmpty()) {
            return "Question: " + question + "\n\nNo excerpts were retrieved.";
        }
        // The valid-label whitelist is placed AFTER the excerpts on purpose: instruction
        // recency beats a rule stated only in the system prompt, and enumerating the exact
        // labels removes any guesswork about which citations can possibly be valid.
        return "Question: " + question
                + "\n\nExcerpts:\n" + context
                + "Valid citation labels for this question: " + String.join(" ", labels) + ". "
                + "Cite only these labels; any other bracketed token is invalid.\n"
                + "Answer now.";
    }

    /**
     * Whether the model refused to answer. Detection is sentinel-FIRST, not
     * sentinel-anywhere, and that distinction was earned the hard way: on the 48-case eval
     * run, three cases produced a full grounded answer and then appended the sentinel as a
     * trailing caveat ("...however the excerpts do not cover X. INSUFFICIENT_CONTEXT").
     * Counting those as refusals mislabeled 3/48 cases. A trailing caveat means "weakly
     * grounded answer"; only a sentinel-first reply means "refusal".
     */
    public boolean isRefusal(String answer) {
        if (answer == null) {
            return false;
        }
        return answer.trim().startsWith(REFUSAL_SENTINEL);
    }

    /**
     * Extracts citation attempts and resolves the well-formed ones back to chunks.
     *
     * @param answer generated answer
     * @param chunks the exact chunk list that was lettered in the prompt
     * @return one entry per bracketed token, in text order; unresolvable tokens are
     *         marked invalid rather than dropped, so citation accuracy stays honest
     */
    public List<CitationRef> parseCitations(String answer, List<Merged> chunks) {
        List<CitationRef> refs = new ArrayList<>();
        if (answer == null || answer.isEmpty()) {
            return refs;
        }
        Matcher matcher = ATTEMPT.matcher(answer);
        while (matcher.find()) {
            String token = matcher.group(0);
            String inside = token.substring(1, token.length() - 1).trim();
            Integer index = LABEL.matcher(inside).matches() ? letterIndex(inside) : null;
            boolean valid = index != null && index < chunks.size();
            refs.add(new CitationRef(
                    token,
                    valid ? index + 1 : 0,
                    valid,
                    valid ? chunks.get(index).chunkId() : ""));
        }
        return refs;
    }

    /**
     * Keeps one citation per distinct chunk, in first-mention order.
     * Deduplication matters because a model often cites the same excerpt repeatedly.
     */
    public List<Citation> distinctCitations(List<CitationRef> refs, List<Merged> chunks) {
        Map<String, Citation> byChunk = new LinkedHashMap<>();
        for (CitationRef ref : refs) {
            if (!ref.valid()) {
                continue;
            }
            int index = ref.ordinal() - 1;
            Merged chunk = chunks.get(index);
            byChunk.putIfAbsent(chunk.chunkId(), new Citation(
                    chunk.chunkId(),
                    chunk.title(),
                    chunk.source(),
                    excerpt(chunk.content()),
                    index));
        }
        return new ArrayList<>(byChunk.values());
    }

    /** Bijective base-26: A -> 0, Z -> 25, AA -> 26. */
    static int letterIndex(String letters) {
        int index = 0;
        for (char c : letters.toUpperCase().toCharArray()) {
            index = index * 26 + (c - 'A' + 1);
        }
        return index - 1;
    }

    /** Inverse of {@link #letterIndex}: 0 -> A, 25 -> Z, 26 -> AA. */
    static String label(int index) {
        StringBuilder sb = new StringBuilder();
        int n = index + 1;
        while (n > 0) {
            n--;
            sb.insert(0, (char) ('A' + n % 26));
            n /= 26;
        }
        return sb.toString();
    }

    private String excerpt(String content) {
        if (content == null) {
            return "";
        }
        String flat = content.replaceAll("\\s+", " ").trim();
        return flat.length() <= 240 ? flat : flat.substring(0, 240) + "...";
    }
}
